### ISSUE TITLE
Interrupting specific sessions

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#162]
Currently in the code...

* When starting a flow we optionally interrupt contacts with `models.InterruptContactRuns`, which interrupts runs and sessions, but _only those of the same flow type_
* During start flow if we fail to write a session and interrupt is true, we call `models.InterruptContactRuns` for that specific contact (bit confused by this..)
* When resuming a session, if the flow for the current run no longer exists, we call `models.InterruptContactRuns` (stuff like this would need to be changed if we have a concept non-interactive flows and thus overlapping sessions cuz currently it interrupts all sessions of same flow type)
* We also have `models.ExitSessions` which exits specific sessions and is currently used when an IVR call finishes, but since it takes `ExitType` as an argument, could interrupt sessions too.

Currently there is no concept of closing the associated connections (i.e. hanging up a call) when interrupting.

I'm wondering if we should have a single way of exiting sessions and runs with a given exit type - and perhaps for convenience another function which calls that with `ExitType==INTERRUPTED`.

This function would look at the sessions to see which have open connections, and close those.

To respect dependencies.. we'd probably need an interface for connections because models can't import IVR code from the `ivr` package because it imports `models`. That interfaace would provide a way for different channel connection types to close themselves.

**Comment by nicpottier** [comment]
IVR interruption is a weird one, because it affects an ongoing call, from a user perspective not sure what the best experience is. You get someone reading you that "Your call has been interrupted?" .. who knows.

Anyways, in Mailroom right now I think some of this has been optimized out. We don't initiate hangups on interruptions because the next callback will do that anyways (the call will be hung up on an error and they will get that error message read to them, which maybe we should take out):
  https://github.com/nyaruka/mailroom/blob/master/ivr/ivr.go#L424

All IVR actions have timeouts and the expiration task takes care of anything else. So really there isn't any need to async go hang up a call, marking the session as interrupted is enough from an IVR point of view.

So I think the current interrupting behavior is just fine.

So back to the root here, we want a task that will interrupt a list of sessions or a list of channel ids ya?

**Comment by nicpottier** [comment]
> (the call will be hung up on an error and they will get that error message read to them, which maybe we should take out)

Oh NM, we do use a canned error message before the hangup: 
  https://github.com/nyaruka/mailroom/blob/master/ivr/ivr.go#L46

**Comment by nicpottier** [comment]
> During start flow if we fail to write a session and interrupt is true, we call models.InterruptContactRuns for that specific contact (bit confused by this..)

Assume you are talking about: 
  https://github.com/nyaruka/mailroom/blob/master/runner/runner.go#L611

This is just a retry per contact, the previous interruption didn't take because the entire transaction rolled back. We are actually trying to write the started flow state here, just for a single contact.

**Comment by rowanseymour** [comment]
Well from the RP pov I think makes most sense to either specify a list of contact_ids or a single channel_id, but obviously that can be implemented as something else internally, i.e. https://github.com/nyaruka/rapidpro/pull/2496/files#diff-48c4ef774f19418e425f28a230c2a004R211

The case with a set of `contact_ids` would interrupt all sessions, but I do think we need to change where we're currently calling `models.InterruptContactRuns` to only interrupt a specific session, no?

**Comment by rowanseymour** [comment]
and is it correct that interrupting for a flow start only interrupts flows of the same type? Seems like flow type shouldn't be relevant there but instead we would be looking at whether the flow is "interactive"

**Comment by nicpottier** [comment]
> and is it correct that interrupting for a flow start only interrupts flows of the same type? Seems like flow type shouldn't be relevant there but instead we would be looking at whether the flow is "interactive"

Do we have a concept of interactive? I think flow type is a reasonable proxy of that since that covers IVR, Messaging and Surveyor. IVR, Messaging and Surveyor can be happening at the same time though, yes.

> I do think we need to change where we're currently calling models.InterruptContactRuns to only interrupt a specific session, no?

Assume you are talking about this?
  https://github.com/nyaruka/mailroom/blob/master/runner/runner.go#L68

Agree could be replaced with a specific Exit. Best case would be for this to be a goflow error so this is all logged in the session and there's no special case at all needed.

What is the minimum needed for your IVR PR and let's start there. We don't want RapidPro to have to create a task to figure out which session ids are needed, so maybe it is just interrupt all IVR sessions associated with this channel id?

**Comment by rowanseymour** [comment]
I've sent https://github.com/nyaruka/rapidpro/pull/2496/files#diff-48c4ef774f19418e425f28a230c2a004R211 a couple of times but I'm guessing you haven't seen it cuz it takes a while to open that crazy diff even on a good connection! 

This is what that PR is currently creating... first for interrupting by contacts, second for interrupting by channel...

```
{
    "type": "interrupt_sessions",
    "org_id": 2352,
    "task": {"org_id": self.org.id, "contact_ids": [23520, 43763], "channel_id": null},
    "queued_on": "2019-08-12T13:11:30.123456Z",
}

{
    "type": "interrupt_sessions",
    "org_id": 2352,
    "task": {"org_id": self.org.id, "contact_ids": null, "channel_id": 1234},
    "queued_on": "2019-08-12T13:11:30.123456Z",
}
```

Re interrupting other runs for flow starts. The [no longer used] behavior in RP is to interrupt all runs for contacts being started, except _system_ flows as we consider those to be non-interactive (campaign message flows). Have we ever allowed contacts to be in both a call and a messaging flow?

**Comment by nicpottier** [comment]
There's all sorts of use cases for IVR and messaging to take place at the same time, don't see any reason to not allow that. (IE, starting a flow to ask for confirmation of a number while on a phone call, etc.. etc..) I discussed this with the team a while back when I made that decision, can't remember whether that was pre or post twist. But yes, that is desired behavior. RP really couldn't deal with it no matter what we wanted. :)

I can open that diff but ya, but that internal HREF doesn't actually resolve for me, probably because Github is paginating it, so ya, didn't know what you were talking about apart from the vague concept that there was something in that diff of interest.

I'm working on a PR for the interruption, should have something in a bit, we implicitely agreed on task names!

**Comment by rowanseymour** [comment]
I'll take your word for it on the flow type discussion - was just comparing with old RP behavior. Guess we also don't have to worry about excluding system/non-interactive flows since they are always written to the database already in a completed state.

**Comment by nicpottier** [comment]
Added.
