### ISSUE TITLE
Webhooks executed before than Send messages

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/mailroom#259]
I've been experiencing a flow that doesn't follow the right execution order, especially on handling with Webhooks. Let's say that I have a flow with the following structure:

1 Parent flow
1.1 Send Message
1.2 Child flow
1.2.1 Webhook

What happens in this case, is that the webhook call is executed before the Send Message node, which keeps waiting until the webhook completes. I would like to fix this issue because it breaks the logic of some flows. Does anyone know what part of the code can I see where this misbehavior happens?

**Comment by nicpottier** [comment]
This is by design, there's no guarantee of the order of sending a message
within a sprint. That's because the flow engine is independent from the
sending, so it runs to completion until a wait and only then processes all
the events that occurred.

This is all part of why the new engine is so much faster than the old in
that all events can be processed and committed in a single transaction
instead of each step being a separate DB hit etc..

**Comment by johncordeiro** [comment]
Hmm, I've got it. In this specific case, what happens is that the user calls a Webhook that tries to get all the messages from that contact and the last ones are always missing (those ones after that previous "Wait for response"). Do you know a better way of doing this?

I was thinking that there's also a need that's very common when we use RapidPro for delivering content to people that are distributed in multiple messages (3 or more). That's the need for a delay between messages. We have the "No response" option but it has a minimum time for 1 minute, do you think that's acceptable to reduce this time for 10/20/30 seconds? It would maybe solve the problem.

**Comment by nicpottier** [comment]
> Hmm, I've got it. In this specific case, what happens is that the user calls a Webhook that tries to get all the messages from that contact and the last ones are always missing (those ones after that previous "Wait for response"). Do you know a better way of doing this?

What are they trying to accomplish here exactly? IE, why do they care that the messages they are sending are in the response? (since supposedly they know what those messages are)

> I was thinking that there's also a need that's very common when we use RapidPro for delivering content to people that are distributed in multiple messages (3 or more). That's the need for a delay between messages. We have the "No response" option but it has a minimum time for 1 minute, do you think that's acceptable to reduce this time for 10/20/30 seconds? It would maybe solve the problem.

Messages are already spaced out by a few seconds automatically. But spacing them out further is a common request and one we have resisted because it is generally people trying to make a bot look like a human, which we oppose from a philosophical perspective. There's a bunch of other details that make it difficult, see: https://github.com/rapidpro/rapidpro/issues/875

**Comment by johncordeiro** [comment]
1) The exact use case: there is a webhook call that creates a room in a [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/) LiveChat, and this API collects the conversation in RapidPro to give as an input to this new room. The room is created, the input is given but with missing messages at the end.

2) I'll take a look at this discussion and contribute.

**Comment by johncordeiro** [comment]
Closing once no solution was found.
