### ISSUE TITLE
Flowrun timeouts calculated incorrectly

### ISSUE THREAD

**Issue by tybritten** [rapidpro/mailroom#369]
Splitting this out from https://github.com/nyaruka/mailroom/issues/279

As mentioned, we're seeing flowrun expirations set as a sum of its timeout plus the timeout of all the subflows in it. So if the parent flow timeout is 2hrs, and it calls 3 sub-flows each with a 2hr timeout, the timeout is put in the db as 8hrs, even if all three of those sub-flows exit within minutes.

**Comment by nicpottier** [comment]
I can repro this and it does seem wrong. I can maybe understand why we initially set the expiration to be the sum while you are three flows down, but once you return to the parent then the expiration should be reset. I'm guessing we maybe have some logic that says we never move expiration to a more recent date and when we return to the parent then that isn't taking effect.

@rowanseymour thoughts? I repro'd on TextIt and flow run expirations are indeed behaving as Tyler describes as set by the flow engine, so this looks to be a goflow bug.

The important distinction here is that activity should move the expiration to a more recent date.

Given two flows, `parent` and `child` each with one hour expirations and a wait in `child`. When you get to the wait in `child` it is reasonable for `parent`'s run to have an expiration that is two hours out, because in the worst case if the contact doesn't reply then they get expired from `child` after one hour (that's considered activity), end up in `parent` and then have another hour before being expired.

But in the case where the contact DOES respond in `child` and gets back to `parent`, the expiration shouldn't be two hours out, but instead only one.
