### ISSUE TITLE
Boundary aliases update timeout

### ISSUE THREAD

**Issue by caioreix** [rapidpro/mailroom#403]
https://github.com/nyaruka/mailroom/blob/303052226c22804d7f6c33b9ac762380f119b228/core/models/assets.go#L77

We are having problems with this timeout interval in locations, when you define a new alias in the adminboundary, it is updated just an hour later. Why is this working like this, and what would affect decreasing this timeout?

**Comment by nicpottier** [comment]
That's a cache like any other. Locations aren't expected to change often. You can restart your mailroom instances if you need to cache bust it earlier.

**Comment by rowanseymour** [comment]
The effect would be increasing the frequency in which you load all the location data for an org. I don't think this an issue for `AdminBoundary` stuff since that's a thing a deployment will update once in a while, and they can restart mailroom if they want those changes to become accessible right away. 

It does tho kinda suck for user made changes to `BoundaryAlias` as I'm sure users expect the changes they make there to take affect right away. Can't think of a simple solution that would disentangle boundaries and their aliases but we could reduce this timeout value and/or make it configurable. Loading locations is not _that_ expensive.

**Comment by caioreix** [comment]
Hello @rowanseymour! Our problem really is when a user updates an alias, we constantly receive support tickets stating that the alias is not working, I think making this timeout configurable is a good solution at the moment.

**Comment by rowanseymour** [comment]
Am looking through our logs and the slowest call to `loadLocations` I can see is ~60ms so I think we can safely reduce that cache timeout significantly.. the other things cache for 5 seconds.. we could say locations cache for a 1 minute? @nicpottier?

**Comment by nicpottier** [comment]
Sure sure.

**Comment by rowanseymour** [comment]
Updated in c38a4fc1e5ede11cbc8249f76964885f33a4ff67
