### ISSUE TITLE
New time options for "continue when there is no response for"

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/mailroom#456]
Hello everyone, after some interviews with users and specialists for chatbot content creation on Rapidpro, we detected that to get humanize the bot, the more time options that less than 1 minute for a wait for a response when "Continue when there is no response for" is enabled is a point very interesting.

We did some changes here and we would like to share them with you. We changed the [value](https://github.com/nyaruka/mailroom/blob/9b268b96d046b38a971f6025533d85c5a6196162/core/tasks/timeouts/cron.go#L33) in seconds (60 to 5 seconds) that is responsible to wait to fire the `cron` every 60 seconds (the minimum value for "Continue when there is no response for" when is enabled). For this, we enabled the minimum value (5 seconds) on the wait for response card on floweditor.

With that, we changed the flow editor and make available other options.
![ss1](https://user-images.githubusercontent.com/10725273/124815888-2fed9d80-df3e-11eb-9889-023d7544a898.png)

We noted that the change brings more processing to the `mailroom`, the `crons` will be running more often depending on the time that changed from 60 seconds to a new value, in this case, listed (5 seconds). Is there a way to make available this value via environment variable on `mailroom` (default value for 60 seconds), and the flow editor can show the minimum value according to that defined on the `mailroom` instance running?

5 seconds is an example, but we have interesting to observe the behavior for `mailroom` running for example with the minimum value of 30 seconds. What do you think? Do you have something in this context to share with us?

Thanks a lot.

**Comment by nicpottier** [comment]
It's confusing since there are so many repos but feature stuff like this should be on rapidpro/rapidpro

This is basically https://github.com/rapidpro/rapidpro/issues/875 which we have had requests for forever. That has some thoughts on how it could be implemented and challenges etc..

I think our current leaning per that ticket is a channel setting that basically is "introduce jitter" that randomly adds a delay when sending messages, perhaps in a configurable window (large, medium, small). Problem is that making any promises with actual second level granularity is making a promise we can't keep at scale and with SMS delays etc..

**Comment by nicpottier** [comment]
Closing as this is in https://github.com/rapidpro/rapidpro/issues/875
